### ISSUE TITLE
[portability] The perf harness's nanosecond clock has no working path on macOS — EPOCHREALTIME is bash 5.0+, and `date +%s%N` is GNU-only

### ISSUE THREAD

**Issue by miztertea** [miztertea/sergeant-rs#95]
Found 2026-08-14 reviewing the #86 bash-3.2 work. **Reasoned from documented behavior, not measured** — this estate has no macOS host yet, so per ADR 0001 this is a claim to verify on the MacBook, not a measurement.

## The shape

Both `perf_now_ns` and `perf_mark` in `scripts/perf/common.sh` use the same two-branch clock:

```sh
local t=${EPOCHREALTIME:-}
if [ -n "$t" ]; then
  ...                      # bash-native, no fork
else
  date +%s%N               # fallback
fi
```

On macOS both branches fail:

- **`EPOCHREALTIME` is a bash 5.0 feature.** macOS ships bash **3.2.57**, frozen for licensing reasons (the same fact ADR 0004's D7 rests on). So the variable is unset and the fallback always fires there — the fast path is never taken on the one platform D7 exists for.
- **`%N` is a GNU coreutils extension.** BSD/macOS `date` does not implement it, so `date +%s%N` emits the epoch seconds followed by a literal `N` — e.g. `1786728341N`.

The result is a non-numeric value fed into a harness that does arithmetic on it. Not a crash; a silently wrong number, which is worse for a measurement harness.

Verified on this host (Linux, bash 5.3.9, GNU coreutils) that both branches work as intended here, which is why it has never surfaced: `EPOCHREALTIME=1786728341.262778`, `date +%s%N=1786728341270736820`.

## Not introduced by #86

Pre-existing in both functions. #86's nameref rewrite (`local -n` → `printf -v`) is correct and does not touch this. Filing separately rather than widening that change's scope — but worth noting the adjacency: #86 makes `scripts/` *syntactically* bash-3.2 clean while the perf harness remains *semantically* broken on the same platform, so "the scripts run on macOS" would be a half-true claim without this.

## Scope

- A nanosecond-resolution clock that works on macOS bash 3.2. Options worth weighing: `python3 -c 'import time; print(time.time_ns())'` (portable, forks — the harness deliberately avoids forks in `perf_mark`, so measure the cost), `perl -MTime::HiRes` (preinstalled on macOS), or accepting millisecond resolution on that platform and recording the degradation rather than hiding it.
- Whichever path, it should fail loudly rather than emit a malformed number — a perf harness that silently produces `1786728341N` is worse than one that refuses to run.
- Verify on the MacBook before closing; that is what makes it measured (ADR 0001).
